"""`setup_path()` must also install a `lemon-acp` launcher.

ACP hosts (Zed, JetBrains, Buzz Desktop) spawn the agent by resolving a command
name against the login-shell PATH. The `lemon-acp` console script generated by
the packaging metadata lives inside the install's venv, which is not on that
PATH, so those hosts report Lemon AI as not installed. `setup_path()` therefore
writes a `lemon-acp` launcher next to the `lemon` one.

These tests drive the real block out of `scripts/install.sh` rather than
asserting on a copy of it, so the shim cannot drift away from the test.
"""

import re
import shlex
import stat
import subprocess
from pathlib import Path
from unittest.mock import patch

INSTALL_SH = Path(__file__).resolve().parent.parent / "scripts" / "install.sh"

ACP_BLOCK = re.compile(
    r'(    rm -f "\$command_link_dir/lemon-acp".*?'
    r'log_success "Installed lemon-acp launcher[^\n]*\n)',
    re.S,
)


def _extract_acp_shim_block() -> str:
    match = ACP_BLOCK.search(INSTALL_SH.read_text(encoding="utf-8"))
    assert match, (
        "could not locate the lemon-acp launcher block in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(1)


def _launcher_prelude(tmp_path: Path, internal: bool) -> str:
    lemon_home = tmp_path / "Lemon AI home"
    return (
        f"LEMON_HOME={shlex.quote(str(lemon_home))}\n"
        f"INTERNAL_DESKTOP_BUILD={'true' if internal else 'false'}\n"
        "launcher_home_export(){ if [ \"$INTERNAL_DESKTOP_BUILD\" = true ]; then printf 'export LEMON_HOME=%q\\n' \"$LEMON_HOME\"; fi; }\n"
    )


def _run_block(tmp_path: Path, use_venv: str, *, internal: bool = False) -> Path:
    """Execute the extracted block with the env vars setup_path() sets."""
    tmp_path.mkdir(parents=True, exist_ok=True)
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    lemon_bin = tmp_path / "venv" / "bin" / "python"
    lemon_bin.parent.mkdir(parents=True)
    lemon_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    entrypoint = tmp_path / "lemon"
    entrypoint.write_text("#!/bin/sh\n", encoding="utf-8")

    script = (
        "set -e\n"
        f"LEMON_BIN={lemon_bin}\n"
        f"LEMON_ENTRYPOINT={entrypoint}\n"
        f"command_link_dir={command_link_dir}\n"
        f"command_link_display_dir={command_link_dir}\n"
        f"USE_VENV={use_venv}\n"
        + _launcher_prelude(tmp_path, internal)
        + "log_success(){ :; }\n" + _extract_acp_shim_block()
    )
    result = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"acp shim block failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / "lemon-acp"


def test_venv_install_writes_executable_acp_launcher(tmp_path):
    shim = _run_block(tmp_path, "true")
    assert shim.is_file()
    assert shim.stat().st_mode & stat.S_IXUSR, "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    # The launcher must dispatch to the ACP subcommand, otherwise the host gets
    # an interactive CLI on stdio and the handshake never completes.
    assert re.search(r'exec .*\bacp\b', text), text


def test_non_venv_install_writes_acp_launcher(tmp_path):
    shim = _run_block(tmp_path, "false")
    text = shim.read_text(encoding="utf-8")
    assert re.search(r'exec .*\bacp\b', text), text


def test_internal_acp_launcher_exports_the_resolved_lemon_home(tmp_path):
    text = _run_block(tmp_path, "true", internal=True).read_text(encoding="utf-8")
    assert "export LEMON_HOME=" in text
    assert str(tmp_path / "Lemon AI home") in text.replace("\\ ", " ")


def test_acp_launcher_does_not_follow_a_symlink_into_the_venv(tmp_path):
    """Guards the #21454 failure mode for the new launcher.

    An older install could leave `lemon-acp` as a symlink to the venv console
    script. Without the `rm -f`, `cat >` follows it and overwrites that script
    with a shim that then execs itself.
    """
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    console_script = tmp_path / "venv" / "bin" / "lemon-acp"
    console_script.parent.mkdir(parents=True)
    marker = "#!/usr/bin/env python\n# real console script\n"
    console_script.write_text(marker, encoding="utf-8")

    shim_path = command_link_dir / "lemon-acp"
    shim_path.symlink_to(console_script)
    assert shim_path.is_symlink()

    lemon_bin = tmp_path / "venv" / "bin" / "python"
    lemon_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    entrypoint = tmp_path / "lemon"
    entrypoint.write_text("#!/bin/sh\n", encoding="utf-8")

    script = (
        "set -e\n"
        f"LEMON_BIN={lemon_bin}\n"
        f"LEMON_ENTRYPOINT={entrypoint}\n"
        f"command_link_dir={command_link_dir}\n"
        f"command_link_display_dir={command_link_dir}\n"
        "USE_VENV=true\n"
        + _launcher_prelude(tmp_path, False)
        + "log_success(){ :; }\n" + _extract_acp_shim_block()
    )
    result = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True, cwd=tmp_path
    )
    assert result.returncode == 0, result.stderr

    assert console_script.read_text(encoding="utf-8") == marker, (
        "venv/bin/lemon-acp was overwritten — symlink-stomp regression (#21454)"
    )
    assert not shim_path.is_symlink(), (
        "command_link_dir/lemon-acp must be replaced with a regular file"
    )


# ---------------------------------------------------------------------------
# lemon-agent launcher regression (#74819)
# ---------------------------------------------------------------------------

LEMON_AGENT_BLOCK = re.compile(
    r'(rm -f "\$command_link_dir/lemon-agent".*?'
    r'log_success "Installed lemon-agent launcher[^\n]*\n)',
    re.S,
)


def _extract_lemon_agent_shim_block() -> str:
    match = LEMON_AGENT_BLOCK.search(INSTALL_SH.read_text(encoding="utf-8"))
    assert match, (
        "could not locate the lemon-agent launcher block in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(1)


def _run_lemon_agent_block(tmp_path: Path, use_venv: str, *, internal: bool = False) -> Path | None:
    """Execute the extracted lemon-agent block with the env vars setup_path() sets."""
    if use_venv == "false":
        # --no-venv: lemon-agent is NOT installed by this block (handled
        # elsewhere), so there's nothing to test here.
        return None

    tmp_path.mkdir(parents=True, exist_ok=True)
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    lemon_bin = tmp_path / "venv" / "bin" / "python"
    lemon_bin.parent.mkdir(parents=True)
    lemon_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    install_dir = tmp_path / "install"
    install_dir.mkdir()

    script = (
        "set -e\n"
        f"LEMON_BIN={lemon_bin}\n"
        f"INSTALL_DIR={install_dir}\n"
        f"command_link_dir={command_link_dir}\n"
        f"command_link_display_dir={command_link_dir}\n"
        f"USE_VENV={use_venv}\n"
        + _launcher_prelude(tmp_path, internal)
        + "log_success(){ :; }\n" + _extract_lemon_agent_shim_block()
    )
    result = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"lemon-agent shim block failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / "lemon-agent"


def test_venv_install_writes_executable_lemon_agent_launcher(tmp_path):
    """venv install must write a user-executable lemon-agent launcher."""
    shim = _run_lemon_agent_block(tmp_path, "true")
    assert shim is not None
    assert shim.is_file()
    assert shim.stat().st_mode & stat.S_IXUSR, "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    assert "run_agent.py" in text, "lemon-agent must dispatch to run_agent.py"


def test_internal_lemon_agent_launcher_exports_the_resolved_lemon_home(tmp_path):
    shim = _run_lemon_agent_block(tmp_path, "true", internal=True)
    assert shim is not None
    text = shim.read_text(encoding="utf-8")
    assert "export LEMON_HOME=" in text
    assert str(tmp_path / "Lemon AI home") in text.replace("\\ ", " ")


def test_ordinary_launchers_do_not_pin_a_desktop_home(tmp_path):
    acp = _run_block(tmp_path / "acp", "true")
    agent = _run_lemon_agent_block(tmp_path / "agent", "true")
    assert agent is not None
    assert "export LEMON_HOME=" not in acp.read_text(encoding="utf-8")
    assert "export LEMON_HOME=" not in agent.read_text(encoding="utf-8")


def test_all_launcher_variants_include_the_internal_home_export_hook():
    source = INSTALL_SH.read_text(encoding="utf-8")
    assert source.count("$(launcher_home_export)") == 6


def test_lemon_agent_launcher_cleanup_on_uninstall(tmp_path):
    """uninstall.remove_wrapper_script() must remove lemon-agent alongside
    lemon and lemon-acp."""
    from lemon_cli.uninstall import remove_wrapper_script

    # Simulate a lemon-agent wrapper in the user-local location
    local_shim = tmp_path / ".local" / "bin" / "lemon-agent"
    local_shim.parent.mkdir(parents=True)
    local_shim.write_text("#!/usr/bin/env bash\nexec lemon-agent\n", encoding="utf-8")

    with patch.object(Path, "home", return_value=tmp_path):
        removed = remove_wrapper_script()

    assert local_shim in removed, "local lemon-agent wrapper must be removed"
